name: verify

on:
  pull_request:


jobs:

  verify:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set rustup profile & toolchain
        run: |
          rustup set profile minimal
          rustup toolchain install stable

      - name: Get timestamp for cache
        id: date
        run: echo "yearmo=$(date +%Y%m)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{steps.date.outputs.yearmo}}

      - name: Cargo fmt
        run: cargo fmt --all -- --check

      - name: Debug build
        run: cargo build --locked --verbose

      - name: Test
        run: cargo test --locked --verbose
